version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app 
    command:
      sh -c 'npm run dev'
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true
    ports:
      - "3000:3000" 
      - "3001:3001"

